---
connection:
  downstream:
    readTimeoutSeconds: 60
    roundTripTimeoutSeconds: 120
    idleTimeoutSeconds: 60
    http:
      port: 8080
    maxBodyBytes: 65535
  upstream:
    socketTimeoutSeconds: 10
    readTimeoutSeconds: 30
    idleTimeoutSeconds: 10
    maxAttempts: 1
    tlsInsecureSkipVerify: true

routes:
  - path: /mse6/
    resource: mse6

resources:
  mse6:
    - url:
        scheme: http://
        host: {{ hostvars['pt-mse61'].ip }}
        port: 8080
